######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 24 13:13:00 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += \
    main.cpp

HEADERS += \
    test1.h



